Add support for loading CSV of LabeledPatients
som-shahlab/femr pull request #144
Opened 2023-05-23 23:31 UTC by Miking98

Updates clmbr create batches dataloader to accept a CSV with the columns: **patient_id, prediction_datetime, label_value** and load that into a LabeledPatient object, instead of a .pkl dump of the LabeledPatient object

2023-05-23 23:39 UTC, Lalaland commented
I heavily disagree with this PR. Having duplicate code to accept multiple label formats across the codebase is going to lead to chaos. 

Input should always be in the LabeledPatient format.

2023-05-23 23:43 UTC, Lalaland commented
Also, generating labels in this way is heavily not recommended. It will be wrong (at least in some aspect) 100% of the time due to shifting time definitions between dataset sources.

I understand we have to support it, but people should realize that they are going to get wrong results when they feed in labels this way.

2023-05-23 23:59 UTC, Miking98 commented
Sure but we're not changing anything about the LabeledPatients format here -- literally just allowing you to dump the LabeledPatient object as a `.csv` instead of a `.pkl` for readability / transferability purposes. 

`LabeledPatient` should be a standard interface that abstracts away the specific storage mechanism you use to store data on disk, so I don't quite understand the issue here?

2023-05-24 00:00 UTC, Miking98 commented
And the CSV labels that we're releasing are only meant to be used with our cohort, so I don't quite see what you mean by "shifting time definitions between dataset sources"? There's only one in our case.

2023-05-24 00:01 UTC, Lalaland commented
> Sure but we're not changing anything about the LabeledPatients format here -- literally just allowing you to dump the LabeledPatient object as a .csv instead of a .pkl for readability / transferability purposes.

I'd really prefer to only have one serialization format for LabeledPatient. If we want to use a csv format, we should use that csv format universally.

2023-05-24 00:05 UTC, Miking98 commented
Sure I'd be in favor of universal `.csv`!

I think ideally there would be a `save_to_disk(fmt)` function within `LabeledPatients` which saved in a variety of file fmts depending on what you wanted. 

But at least in our case, a `.pkl` file doesn't make much sense since (1) someone might want to use the few-shot dataset without FEMR (which would be impossible with a `.pkl` file which requires FEMR to import that object), (2) `.csv` is much easier to inspect.

So would probably vote to shift to `.csv`

2023-05-24 00:10 UTC, Miking98 commented
I mean we already do this with the `load_from_numpy` and `as_list_of_label_tuples` and `as_numpy_arrays` functions, no (i.e. shifting between data formats)?

2023-05-24 00:10 UTC, Lalaland commented
> I think ideally there would be a save_to_disk(fmt) function within LabeledPatients which saved in a variety of file fmts depending on what you wanted.

Supporting multiple file formats for anything other than legacy support seems like a maintenance headache. 

If you think we should move over to csvs, let's move over to csvs.

2023-05-24 00:47 UTC, Lalaland requested changes

2023-05-24 00:47 UTC, Lalaland commented on src/femr/labelers/core.py
> +        patients_to_labels[row["patient_id"]].append(Label(time=row["prediction_datetime"], value=row["label_value"]))
This code is incorrect. It doesn't properly handle time to event label values.

2023-05-24 18:00 UTC, closed without merging