Updated MIMIC ETL and transforms
som-shahlab/femr pull request #155
Opened 2023-07-11 15:08 UTC by joshualemmon

Adding custom transform and ETL for MIMIC-IV to handle data errors present in source data.
A small number of visits in the original MIMIC-IV data have a end date that occurs before the start date, which is causing the labeling functions to break.

The MIMIC ETL takes visits where the end date occurs before the start date and replaces the erroneous end date with the start date. This fixes the issues that were causing the labeling functions to break.

2023-07-11 22:04 UTC, Lalaland requested changes
Looks mostly good with one minor comment.

Please revert the tutorial changes though. You seem to have copied some old tutorial stuff into this PR?

2023-07-11 22:04 UTC, Lalaland commented on src/femr/transforms/mimic.py
> +    patient.resort()
This call is not necessary, but feel free to keep it.

2023-07-13 21:37 UTC, guolin1 commented
Started from main and re-added @joshualemmon 's MIMIC transforms and ETL.

2023-07-13 23:02 UTC, Lalaland approved these changes

2023-07-14 00:02 UTC, merged