Update README.md
som-shahlab/femr pull request #194
Opened 2024-03-26 04:02 UTC by Miking98

Update readme with instructions

2024-03-26 15:18 UTC, EthanSteinberg requested changes
Yeah, we really need this additional documentation. Two minor fixes to it though.

2024-03-26 15:18 UTC, EthanSteinberg commented on README.md
> +pip install meds meds-etl
With the addition of meds_etl to the dependency list, I guess this isn't necessary anymore?

2024-03-26 15:18 UTC, EthanSteinberg commented on README.md
> +meds_etl_omop [PATH_TO_SOURCE_OMOP] [PATH_TO_OUTPUT_MEDS]
We are missing the stanford omop fixer call: https://github.com/som-shahlab/femr/blob/main/src/femr/post_etl_pipelines/stanford.py#L50

2024-03-27 00:44 UTC, closed without merging

2024-03-27 00:48 UTC, EthanSteinberg commented
Shoot, accidentally broke this MR. Super sorry about that @Miking98. You should be able to recreate and reopen it.

2024-03-28 20:11 UTC, Miking98 commented
No worries, will reopen!