A MIMIC -> Piton tutorial
som-shahlab/femr pull request #81
Opened 2023-02-09 23:05 UTC by Lalaland

This is a first draft of a MIMIC -> Piton tutorial.

The goal was as simple as an ETL as possible with minimal data loss.

The main difference between this and a real ETL is that a real ETL would try to actually map things to OMOP standard concepts. This does exactly zero mapping.

2023-02-09 23:19 UTC, Lalaland commented
Closes #80

2023-02-09 23:23 UTC, Lalaland commented
Also will close #61

2023-02-26 00:32 UTC, jason-fries requested changes
@Lalaland See some clarification question on version support.

2023-02-26 00:32 UTC, jason-fries commented on native/database.cc
> +            absl::StrCat("Cannot have a birth date before epoch (1800) ",
Can we add some comments here on why these values are chosen? A new person walking in will have zero idea why 1800 was chosen as a sensible minimum birthdate.

2023-02-26 00:32 UTC, jason-fries commented on src/piton/etl_pipelines/omop.py
> +    soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE)
Again, some code comments would go a long way. What are these doing? Why do we set them?

2023-02-26 00:32 UTC, jason-fries commented on native/database.cc
> +constexpr uint32_t current_version = 3;
Will this branch support prior versions? for example, can I keep using the v7 extract after merging this branch into main?

2023-02-26 07:30 UTC, merged